# Generated by Django 6.0.6 on 2026-06-29 15:44

import django.db.models.deletion
import django.utils.timezone
import incidencias.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de incidencia',
                'verbose_name_plural': 'Categorías de incidencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ROUTER_PRINCIPAL', 'Router principal'), ('ROUTER', 'Router'), ('SWITCH', 'Switch'), ('RADIO_AP', 'Radio AP / Sectorial'), ('BACKHAUL', 'Backhaul'), ('UPS', 'UPS / Energía'), ('FIREWALL', 'Firewall'), ('OLT', 'OLT'), ('SERVIDOR', 'Servidor'), ('OTRO', 'Otro')], max_length=30)),
                ('funcion', models.CharField(choices=[('NODO_PRINCIPAL', 'Nodo principal'), ('SECTORIAL', 'Sectorial'), ('TRANSPORTE', 'Transporte'), ('DISTRIBUCION', 'Distribución'), ('ENERGIA', 'Energía'), ('SEGURIDAD', 'Seguridad'), ('MONITOREO', 'Monitoreo'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('ip_gestion', models.GenericIPAddressField(blank=True, null=True, unique=True, unpack_ipv4=True)),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('host_id_zabbix', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('es_monitoreado_zabbix', models.BooleanField(default=True)),
                ('impacto_por_caida', models.CharField(choices=[('NODO_COMPLETO', 'Nodo completo'), ('SECTORIAL', 'Sectorial'), ('COMPONENTE', 'Componente específico')], default='COMPONENTE', max_length=30)),
                ('estado_operativo', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('CAIDO', 'Caído'), ('MANTENIMIENTO', 'Mantenimiento'), ('RETIRADO', 'Retirado')], default='OPERATIVO', max_length=30)),
                ('criticidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=30)),
                ('clientes_estimados', models.PositiveIntegerField(default=0)),
                ('datos_tecnicos_json', models.JSONField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Componente de red',
                'verbose_name_plural': 'Componentes de red',
                'ordering': ['nodo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='AlertaZabbix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('trigger_id', models.CharField(blank=True, max_length=100, null=True)),
                ('problem_id', models.CharField(blank=True, max_length=100, null=True)),
                ('recovery_event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('host_id', models.CharField(max_length=100)),
                ('nombre_alerta', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('severidad', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=30)),
                ('estado_zabbix', models.CharField(choices=[('PROBLEM', 'Problema'), ('RESOLVED', 'Resuelto')], default='PROBLEM', max_length=30)),
                ('fecha_evento', models.DateTimeField()),
                ('fecha_recuperacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion_sistema', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged', models.BooleanField(default=False)),
                ('procesada', models.BooleanField(default=False)),
                ('datos_json', models.JSONField(blank=True, null=True)),
                ('tags_json', models.JSONField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('componente_red', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alertas_zabbix', to='incidencias.componentered')),
            ],
            options={
                'verbose_name': 'Alerta Zabbix',
                'verbose_name_plural': 'Alertas Zabbix',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(default=incidencias.models.generar_codigo_incidencia, editable=False, max_length=40, unique=True)),
                ('ticket_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('origen', models.CharField(choices=[('ZABBIX', 'Zabbix'), ('MANUAL', 'Manual'), ('CORREO', 'Correo'), ('TELEFONO', 'Teléfono'), ('WHATSAPP', 'WhatsApp'), ('OTRO', 'Otro')], default='ZABBIX', max_length=30)),
                ('tipo_afectacion', models.CharField(choices=[('NODO_COMPLETO', 'Nodo completo'), ('SECTORIAL', 'Sectorial'), ('COMPONENTE', 'Componente específico')], default='COMPONENTE', max_length=30)),
                ('severidad', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=30)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=30)),
                ('estado', models.CharField(choices=[('DETECTADA', 'Detectada'), ('REGISTRADA', 'Registrada'), ('ASIGNADA', 'Asignada'), ('EN_ATENCION', 'En atención'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], default='DETECTADA', max_length=30)),
                ('clientes_afectados_estimados', models.PositiveIntegerField(default=0)),
                ('fecha_deteccion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_asignacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio_atencion', models.DateTimeField(blank=True, null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('solucion', models.TextField(blank=True, null=True)),
                ('causa_raiz', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cumple_sla_registro', models.BooleanField(blank=True, null=True)),
                ('cumple_sla_asignacion', models.BooleanField(blank=True, null=True)),
                ('cumple_sla_inicio_atencion', models.BooleanField(blank=True, null=True)),
                ('cumple_sla_resolucion', models.BooleanField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('alerta_zabbix', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencia', to='incidencias.alertazabbix')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='incidencias.categoriaincidencia')),
                ('componente_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_principales', to='incidencias.componentered')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='HistorialIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('ASIGNACION', 'Asignación'), ('REASIGNACION', 'Reasignación'), ('NOTIFICACION', 'Notificación'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('CAMBIO_SEVERIDAD', 'Cambio de severidad'), ('ATENCION', 'Atención'), ('DIAGNOSTICO', 'Diagnóstico'), ('RESOLUCION', 'Resolución'), ('CIERRE', 'Cierre'), ('CANCELACION', 'Cancelación'), ('COMENTARIO', 'Comentario'), ('EVIDENCIA', 'Evidencia')], max_length=100)),
                ('estado_anterior', models.CharField(blank=True, choices=[('DETECTADA', 'Detectada'), ('REGISTRADA', 'Registrada'), ('ASIGNADA', 'Asignada'), ('EN_ATENCION', 'En atención'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], max_length=30, null=True)),
                ('estado_nuevo', models.CharField(blank=True, choices=[('DETECTADA', 'Detectada'), ('REGISTRADA', 'Registrada'), ('ASIGNADA', 'Asignada'), ('EN_ATENCION', 'En atención'), ('RESUELTA', 'Resuelta'), ('CERRADA', 'Cerrada'), ('CANCELADA', 'Cancelada')], max_length=30, null=True)),
                ('campo_modificado', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_anterior', models.TextField(blank=True, null=True)),
                ('valor_nuevo', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_incidencias', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='incidencias.incidencia')),
            ],
            options={
                'verbose_name': 'Historial de incidencia',
                'verbose_name_plural': 'Historial de incidencias',
                'ordering': ['-fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='EvidenciaIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo', models.FileField(upload_to='evidencias_incidencias/%Y/%m/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_incidencias', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='incidencias.incidencia')),
            ],
            options={
                'verbose_name': 'Evidencia de incidencia',
                'verbose_name_plural': 'Evidencias de incidencias',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comentario', models.TextField()),
                ('tipo_comentario', models.CharField(choices=[('SEGUIMIENTO', 'Seguimiento'), ('DIAGNOSTICO', 'Diagnóstico'), ('SOLUCION', 'Solución'), ('ESCALAMIENTO', 'Escalamiento'), ('OBSERVACION', 'Observación')], default='SEGUIMIENTO', max_length=30)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios_incidencias', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='incidencias.incidencia')),
            ],
            options={
                'verbose_name': 'Comentario de incidencia',
                'verbose_name_plural': 'Comentarios de incidencias',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='incidencias.incidencia')),
            ],
            options={
                'verbose_name': 'Asignación de incidencia',
                'verbose_name_plural': 'Asignaciones de incidencias',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='IncidenciaComponenteAfectado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tipo_impacto', models.CharField(choices=[('DIRECTO', 'Directo'), ('INDIRECTO', 'Indirecto')], default='DIRECTO', max_length=30)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('componente_red', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afectaciones', to='incidencias.componentered')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_afectados_detalle', to='incidencias.incidencia')),
            ],
            options={
                'verbose_name': 'Componente afectado',
                'verbose_name_plural': 'Componentes afectados',
                'ordering': ['incidencia', 'componente_red'],
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='componentes_afectados',
            field=models.ManyToManyField(blank=True, related_name='incidencias_afectadas', through='incidencias.IncidenciaComponenteAfectado', to='incidencias.componentered'),
        ),
        migrations.CreateModel(
            name='LogIntegracionZabbix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('proceso', models.CharField(choices=[('CONSULTA_ALERTAS', 'Consulta de alertas'), ('CREACION_ALERTA', 'Creación de alerta'), ('CREACION_INCIDENCIA', 'Creación de incidencia'), ('ACTUALIZACION_ALERTA', 'Actualización de alerta'), ('ACTUALIZACION_INCIDENCIA', 'Actualización de incidencia'), ('SINCRONIZACION_HOSTS', 'Sincronización de hosts')], max_length=100)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('ERROR', 'Error'), ('PARCIAL', 'Parcial')], max_length=30)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('total_alertas', models.PositiveIntegerField(default=0)),
                ('total_procesadas', models.PositiveIntegerField(default=0)),
                ('total_errores', models.PositiveIntegerField(default=0)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('detalle_json', models.JSONField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de integración Zabbix',
                'verbose_name_plural': 'Logs de integración Zabbix',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('direccion_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('MANTENIMIENTO', 'Mantenimiento')], default='ACTIVO', max_length=30)),
                ('criticidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=30)),
                ('clientes_estimados', models.PositiveIntegerField(default=0)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nodo',
                'verbose_name_plural': 'Nodos',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='nodo_afectado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='incidencias.nodo'),
        ),
        migrations.AddField(
            model_name='componentered',
            name='nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes_red', to='incidencias.nodo'),
        ),
        migrations.CreateModel(
            name='NotificacionIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('medio', models.CharField(choices=[('SISTEMA', 'Sistema'), ('CORREO', 'Correo'), ('WHATSAPP', 'WhatsApp'), ('TELEFONO', 'Teléfono'), ('ZABBIX', 'Zabbix'), ('OTRO', 'Otro')], default='SISTEMA', max_length=30)),
                ('destinatario', models.CharField(blank=True, max_length=150, null=True)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=30)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='incidencias.incidencia')),
                ('usuario_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_incidencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de incidencia',
                'verbose_name_plural': 'Notificaciones de incidencias',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('GESTOR_NOC', 'Gestor NOC'), ('TECNICO', 'Técnico'), ('SUPERVISOR', 'Supervisor'), ('VENDEDOR', 'Vendedor'), ('DUENO', 'Dueño')], default='TECNICO', max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('disponible', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_incidencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de usuario',
                'verbose_name_plural': 'Perfiles de usuarios',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='SLAIncidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('severidad', models.CharField(choices=[('INFORMATIVA', 'Informativa'), ('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('tiempo_max_registro_min', models.PositiveIntegerField(default=10)),
                ('tiempo_max_asignacion_min', models.PositiveIntegerField(default=15)),
                ('tiempo_max_inicio_atencion_min', models.PositiveIntegerField(default=30)),
                ('tiempo_max_resolucion_min', models.PositiveIntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SLA de incidencia',
                'verbose_name_plural': 'SLAs de incidencias',
                'ordering': ['severidad'],
            },
        ),
        migrations.AddField(
            model_name='incidencia',
            name='sla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias', to='incidencias.slaincidencia'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ['departamento', 'provincia', 'distrito', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='nodo',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodos', to='incidencias.ubicacion'),
        ),
        migrations.AddIndex(
            model_name='categoriaincidencia',
            index=models.Index(fields=['activo'], name='incidencias_activo_a327da_idx'),
        ),
        migrations.AddIndex(
            model_name='alertazabbix',
            index=models.Index(fields=['event_id'], name='incidencias_event_i_e706dd_idx'),
        ),
        migrations.AddIndex(
            model_name='alertazabbix',
            index=models.Index(fields=['trigger_id'], name='incidencias_trigger_c7e377_idx'),
        ),
        migrations.AddIndex(
            model_name='alertazabbix',
            index=models.Index(fields=['problem_id'], name='incidencias_problem_f71ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='alertazabbix',
            index=models.Index(fields=['host_id'], name='incidencias_host_id_bfea11_idx'),
        ),
        migrations.AddIndex(
            model_name='alertazabbix',
            index=models.Index(fields=['estado_zabbix'], name='incidencias_estado__6d930f_idx'),
        ),
        migrations.AddIndex(
            model_name='alertazabbix',
            index=models.Index(fields=['severidad'], name='incidencias_severid_3d29f2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertazabbix',
            index=models.Index(fields=['fecha_evento'], name='incidencias_fecha_e_13eb8f_idx'),
        ),
        migrations.AddIndex(
            model_name='alertazabbix',
            index=models.Index(fields=['procesada'], name='incidencias_procesa_07d646_idx'),
        ),
        migrations.AddIndex(
            model_name='historialincidencia',
            index=models.Index(fields=['accion'], name='incidencias_accion_69c1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='historialincidencia',
            index=models.Index(fields=['estado_anterior'], name='incidencias_estado__f144fd_idx'),
        ),
        migrations.AddIndex(
            model_name='historialincidencia',
            index=models.Index(fields=['estado_nuevo'], name='incidencias_estado__776879_idx'),
        ),
        migrations.AddIndex(
            model_name='historialincidencia',
            index=models.Index(fields=['fecha_evento'], name='incidencias_fecha_e_611a37_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarioincidencia',
            index=models.Index(fields=['tipo_comentario'], name='incidencias_tipo_co_727616_idx'),
        ),
        migrations.AddIndex(
            model_name='comentarioincidencia',
            index=models.Index(fields=['creado_en'], name='incidencias_creado__287e0d_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionincidencia',
            index=models.Index(fields=['fecha_asignacion'], name='incidencias_fecha_a_557007_idx'),
        ),
        migrations.AddIndex(
            model_name='asignacionincidencia',
            index=models.Index(fields=['activo'], name='incidencias_activo_e16b96_idx'),
        ),
        migrations.AddIndex(
            model_name='incidenciacomponenteafectado',
            index=models.Index(fields=['tipo_impacto'], name='incidencias_tipo_im_404df2_idx'),
        ),
        migrations.AddConstraint(
            model_name='incidenciacomponenteafectado',
            constraint=models.UniqueConstraint(fields=('incidencia', 'componente_red'), name='unique_componente_afectado_por_incidencia'),
        ),
        migrations.AddIndex(
            model_name='logintegracionzabbix',
            index=models.Index(fields=['proceso'], name='incidencias_proceso_d320ae_idx'),
        ),
        migrations.AddIndex(
            model_name='logintegracionzabbix',
            index=models.Index(fields=['estado'], name='incidencias_estado_241fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='logintegracionzabbix',
            index=models.Index(fields=['fecha_inicio'], name='incidencias_fecha_i_e4b39d_idx'),
        ),
        migrations.AddIndex(
            model_name='componentered',
            index=models.Index(fields=['codigo'], name='incidencias_codigo_deb8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='componentered',
            index=models.Index(fields=['nombre'], name='incidencias_nombre_6d3ec3_idx'),
        ),
        migrations.AddIndex(
            model_name='componentered',
            index=models.Index(fields=['tipo'], name='incidencias_tipo_08c547_idx'),
        ),
        migrations.AddIndex(
            model_name='componentered',
            index=models.Index(fields=['funcion'], name='incidencias_funcion_85f2cd_idx'),
        ),
        migrations.AddIndex(
            model_name='componentered',
            index=models.Index(fields=['host_id_zabbix'], name='incidencias_host_id_a21861_idx'),
        ),
        migrations.AddIndex(
            model_name='componentered',
            index=models.Index(fields=['estado_operativo'], name='incidencias_estado__b3a0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='componentered',
            index=models.Index(fields=['criticidad'], name='incidencias_critici_d8fc48_idx'),
        ),
        migrations.AddIndex(
            model_name='componentered',
            index=models.Index(fields=['activo'], name='incidencias_activo_216913_idx'),
        ),
        migrations.AddConstraint(
            model_name='componentered',
            constraint=models.UniqueConstraint(fields=('nodo', 'codigo'), name='unique_componente_red_por_nodo'),
        ),
        migrations.AddIndex(
            model_name='notificacionincidencia',
            index=models.Index(fields=['medio'], name='incidencias_medio_845064_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionincidencia',
            index=models.Index(fields=['estado'], name='incidencias_estado_c0baf8_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacionincidencia',
            index=models.Index(fields=['fecha_envio'], name='incidencias_fecha_e_b587e1_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['rol'], name='incidencias_rol_a4faeb_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['activo'], name='incidencias_activo_d3c6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='perfilusuario',
            index=models.Index(fields=['disponible'], name='incidencias_disponi_b45cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='slaincidencia',
            index=models.Index(fields=['severidad'], name='incidencias_severid_e0d7aa_idx'),
        ),
        migrations.AddIndex(
            model_name='slaincidencia',
            index=models.Index(fields=['activo'], name='incidencias_activo_711825_idx'),
        ),
        migrations.AddConstraint(
            model_name='slaincidencia',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_max_registro_min__gt', 0)), name='sla_registro_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='slaincidencia',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_max_asignacion_min__gt', 0)), name='sla_asignacion_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='slaincidencia',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_max_inicio_atencion_min__gt', 0)), name='sla_inicio_atencion_mayor_cero'),
        ),
        migrations.AddConstraint(
            model_name='slaincidencia',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_max_resolucion_min__gt', 0)), name='sla_resolucion_mayor_cero'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['codigo'], name='incidencias_codigo_d95dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['ticket_externo'], name='incidencias_ticket__2be17c_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['origen'], name='incidencias_origen_4da717_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['tipo_afectacion'], name='incidencias_tipo_af_f11808_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['estado'], name='incidencias_estado_1b1ac6_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['severidad'], name='incidencias_severid_9b7b6b_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['prioridad'], name='incidencias_priorid_c1fd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_deteccion'], name='incidencias_fecha_d_8232f0_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_registro'], name='incidencias_fecha_r_78c526_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_asignacion'], name='incidencias_fecha_a_726c3a_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_inicio_atencion'], name='incidencias_fecha_i_34aa69_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_resolucion'], name='incidencias_fecha_r_338d85_idx'),
        ),
        migrations.AddIndex(
            model_name='incidencia',
            index=models.Index(fields=['fecha_cierre'], name='incidencias_fecha_c_e6ddc6_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['departamento'], name='incidencias_departa_61921e_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['provincia'], name='incidencias_provinc_6c4a60_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['distrito'], name='incidencias_distrit_99826f_idx'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['activo'], name='incidencias_activo_c6ff15_idx'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__isnull', True), models.Q(('latitud__gte', -90), ('latitud__lte', 90)), _connector='OR'), name='ubicacion_latitud_valida'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__isnull', True), models.Q(('longitud__gte', -180), ('longitud__lte', 180)), _connector='OR'), name='ubicacion_longitud_valida'),
        ),
        migrations.AddIndex(
            model_name='nodo',
            index=models.Index(fields=['codigo'], name='incidencias_codigo_ddee56_idx'),
        ),
        migrations.AddIndex(
            model_name='nodo',
            index=models.Index(fields=['nombre'], name='incidencias_nombre_ae39f0_idx'),
        ),
        migrations.AddIndex(
            model_name='nodo',
            index=models.Index(fields=['estado'], name='incidencias_estado_aa6bcb_idx'),
        ),
        migrations.AddIndex(
            model_name='nodo',
            index=models.Index(fields=['criticidad'], name='incidencias_critici_79fcc2_idx'),
        ),
        migrations.AddIndex(
            model_name='nodo',
            index=models.Index(fields=['activo'], name='incidencias_activo_11f483_idx'),
        ),
        migrations.AddConstraint(
            model_name='nodo',
            constraint=models.CheckConstraint(condition=models.Q(('latitud__isnull', True), models.Q(('latitud__gte', -90), ('latitud__lte', 90)), _connector='OR'), name='nodo_latitud_valida'),
        ),
        migrations.AddConstraint(
            model_name='nodo',
            constraint=models.CheckConstraint(condition=models.Q(('longitud__isnull', True), models.Q(('longitud__gte', -180), ('longitud__lte', 180)), _connector='OR'), name='nodo_longitud_valida'),
        ),
    ]
