# Generated by Django 6.0.6 on 2026-07-09 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionZabbix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('nombre', models.CharField(default='Servidor Zabbix Principal', max_length=100)),
                ('url_api', models.URLField(help_text='URL de la API de Zabbix. Ejemplo: http://192.168.1.10/zabbix/api_jsonrpc.php', max_length=255)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('token_api', models.TextField(blank=True, help_text='Token API de Zabbix, si se usa autenticación por token.', null=True)),
                ('usar_token', models.BooleanField(default=False)),
                ('ultima_prueba_conexion', models.DateTimeField(blank=True, null=True)),
                ('conexion_exitosa', models.BooleanField(default=False)),
                ('mensaje_ultima_prueba', models.TextField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración Zabbix',
                'verbose_name_plural': 'Configuraciones Zabbix',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo'], name='incidencias_activo_d5f421_idx'), models.Index(fields=['conexion_exitosa'], name='incidencias_conexio_102773_idx')],
            },
        ),
    ]
