# Generated by Django 6.0.6 on 2026-08-23 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_configuracionzabbix'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='slaincidencia',
            name='genera_incidencia_automatica',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='slaincidencia',
            name='tiempo_confirmacion_zabbix_min',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddConstraint(
            model_name='slaincidencia',
            constraint=models.CheckConstraint(condition=models.Q(('tiempo_confirmacion_zabbix_min__gt', 0)), name='sla_confirmacion_zabbix_mayor_cero'),
        ),
    ]
