# Generated by Django 6.0.6 on 2026-08-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_slaincidencia_genera_incidencia_automatica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionincidencia',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura'),
        ),
        migrations.AddField(
            model_name='notificacionincidencia',
            name='leida',
            field=models.BooleanField(default=False, verbose_name='Leída'),
        ),
    ]
